apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-app-deploy
  labels:
    app: ecomm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomm-app
  template:
    metadata:
      labels:
        app: ecomm-app
    spec:
      containers:
      - name: ecomm-app-container
        # Replace 'your-dockerhub-username' with your actual container registry name
        image: arunkumar9080/ecomjava-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # Passes the target database parameters directly as internal system environment values
        - name: DB_URL
          value: "jdbc:mysql://mysql-service:3306/ecommjava?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        - name: DB_USERNAME
          value: "arun"
        - name: DB_PASSWORD
          value: "Popp77038@arun"
---
apiVersion: v1
kind: Service
metadata:
  name: ecomm-app-service
  annotations:
    # 1. Force the Auto Mode controller to use these exact subnets
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0e644243c1decc320, subnet-0eedc28f70acb66d, subnet-00f2fe52d94f1a97c, subnet-05ec9c06d3546b34b"
    
    # 2. Specify that this is an internet-facing public load balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: ecomm-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080